spring:
  application:
    name: myspringboot
  output:
    ansi:
      enabled: always
  profiles:
    active: dev
  thymeleaf:
      prefix: classpath:/templates/
  redis:
      database: 0
      host: 192.168.44.129
      port: 6379
      password: root
      jedis:
        pool:
          max-active: 200
          max-idle: 10
          max-wait: -1
          min-idle: 0
server:
  tomcat:
    uri-encoding: UTF-8
    max-connections: 500
    min-spare-threads: 25
    max-threads: 300
    accept-count: 200
  port: 8090